# Generated by Django 5.0.1 on 2024-03-12 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MapanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=9)),
                ('address', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('eventType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventtype')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organizer')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
