# Generated by Django 5.0.1 on 2024-03-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='instagram',
            field=models.URLField(default='https://www.instagram'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='linkedin',
            field=models.URLField(default='https://www.linkedin.com'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='twitter',
            field=models.URLField(default='https://www.twitter.com'),
        ),
    ]
