# Generated by Django 5.0.1 on 2024-03-13 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_organizer_facebook_alter_organizer_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapanevent',
            name='eventType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventtype', verbose_name='eventtype.label'),
        ),
    ]
