# Generated by Django 5.0.1 on 2024-03-13 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_mapanevent_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapanevent',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mapanevent',
            name='eventType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventtype', verbose_name='type'),
        ),
    ]
