# Generated by Django 5.0.1 on 2024-03-13 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mapanevent_updated_alter_mapanevent_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizer',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
