# Generated by Django 5.0.1 on 2024-03-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_organizer_options_alter_organizer_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='lastname',
        ),
    ]
