# Generated by Django 5.0.1 on 2024-03-14 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_organizer_firstname_remove_organizer_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapanevent',
            name='eventType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventtype'),
        ),
    ]
