# Generated by Django 5.0.3 on 2024-04-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_mapanevent_eventtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizer',
            options={'ordering': ['username']},
        ),
    ]
